# Generated by Django 2.2.1 on 2019-11-05 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRentados',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
