# Generated by Django 2.2.1 on 2019-11-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores_categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('libro_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('pub_date', models.TextField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores_categorias.Autores')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores_categorias.Categorias')),
            ],
        ),
    ]
